version: '3.3'

services:
  go:
    container_name: go
    build:
      context: ./go
      dockerfile: Dockerfile
    tty: true
    ports:
      - 80:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./go
        target: /go/src
    networks:
      - golang_test_network

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
    networks:
      - golang_test_network

volumes:
  mysql_test_volume:
    # name: mysql_test_volume

networks:
  golang_test_network:
    external: true