version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./go
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./go
        target: /go/src
    networks:
      - golang_test_network

  react:
    container_name: react
    build:
      context: ./react_app
      dockerfile: Dockerfile
    volumes:
      - ./react_app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
    networks:
      - golang_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true